name: Build and push docker image

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Main Branch
      uses: actions/checkout@v2
      with:
          ref: 'main'
    - name: Docker login
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    - name: Build image
      run: docker build -t oeken/golang-ubuntu:1.17.6 .
    # - name: Push image
    #   run: docker push oeken/golang-ubuntu:1.17.6


