name: Build and push Go Ubuntu image

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Main Branch
      uses: actions/checkout@v2
      with:
          ref: 'main'
    - name: Build image
      run: docker build -t oeken/golang-ubuntu:1.17.6 .
    - name: Docker login
      run: docker login --username -eken --password-stdin
      with:
        accesToken: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    # - name: Push image
      # run: docker push oeken/golang-ubuntu:1.17.6
